title:            Scribble
description:      Jekyll for recipes. Because I scribble.
baseurl:          /scribble/
url:              http://roachhd.github.io/scribble/
signoff:          Katie Ball.
disqus_shortname: kbscribble
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          /scribble/about
  - name:         Blog
    url:          /scribble/
  - name:         Email
    url:          mailto:scribble@roachhd.com
    external:     true
  - name:         GitHub
    url:          http://github.com/roachhd/scribble
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
